### ISSUE TITLE
Game crashes whenever i use this mod

### ISSUE THREAD

**Issue by San-Fran-Cisco** [ModLabsCC/PermaSnow#3]
anytime it's crashing because of various entity ticking

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_1959.handler$zlk000$permasnow$getPrecipitationAt(class_1959.java:527)
	at knot//net.minecraft.class_1959.method_48162(class_1959.java)
	at knot//net.minecraft.class_1937.method_8520(class_1937.java:810)
	at knot//net.minecraft.class_1297.method_5778(class_1297.java:1323)
	at knot//net.minecraft.class_1297.method_5637(class_1297.java:1335)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:426)
	at knot//net.minecraft.class_1308.method_5670(class_1308.java:284)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:474)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:351)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:chicken (net.minecraft.class_1428)
	Entity ID: 24
	Entity Name: Chicken
	Entity's Exact location: 85.00, 79.00, 341.00
	Entity's Block location: World: (85,79,341), Section: (at 5,15,5 in 5,4,21; chunk contains blocks 80,-64,336 to 95,319,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

Like here, that time it was a chicken, lst time was panda

**Comment by San-Fran-Cisco** [comment]
-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_1959.handler$zmh000$permasnow$getPrecipitationAt(class_1959.java:527)
	at knot//net.minecraft.class_1959.method_48162(class_1959.java)
	at knot//net.minecraft.class_3218.method_18203(class_3218.java:501)
	at knot//net.minecraft.class_3215.method_14161(class_3215.java:382)
	at knot//net.minecraft.class_3215.method_12127(class_3215.java:326)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:333)

-- Affected level --
Details:
	All players: 1 total; [class_3222['San_Fran_Cisco'/137, l='ServerLevel[New Worldfseaasf]', x=-21.50, y=70.00, z=50.50]]
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,76,48), Section: (at 0,12,0 in -2,4,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 5 game time, 5 day time
	Level name: New Worldfseaasf
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 134845 (now: false), thunder time: 55681 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)

i used Neruina to fix the ticking entity, but it still crashes

**Comment by InvalidJoker** [comment]
should be fixed
